### PR TITLE
Jorge flores

### PR DESCRIPTION
**Pull request by JorgeLuisFlores**
Hey Ray,

I'm currently stuck trying to fix this Nav Bar, could you give me any feedback?
Also wanted to see if I did the pull request correctly.

Thank you!

### CODE REVIEW

**Comment by raypugh07** [comment]
I will check it out shortly!

**Comment by raypugh07** [comment]
Putting the logo as a background image is an interesting and not terrible solution but it makes it harder to align. Try putting it back into the html and wrapping it inside the header but outside of the nav. A clue here is that not every class needs to be inline block. Only where it actually helps.

**Comment by raypugh07** [comment]
I left a comment on the pull request. You did indeed do it correctly.

**Comment by JorgeLuisFlores** [comment]
Awesome, that feedback is crucial.
Thank you, Ray!

**Comment by JorgeLuisFlores** [comment]
Hey Ray,

This 2nd pull request was a little bit more confusing, did I do it correctly?
Also finished the project for UI2, if you could please review.

Thank you!

**Comment by raypugh07** [comment]
Overall the general concepts of inline and box are here so good job. Think about how going forward you're going to avoid using the position property for alignment and instead box model properties(content,padding,border,margin). Being able to use flex-box will help. The get started button is slightly off but I won't dock ya for that. Very good job sticking to inline-block with the middle and lower text sections. This meets MVP.

**Pull request merged**
